apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherforecast-api
spec:
  replicas: 3 # Ensures 3 instances are running
  selector:
    matchLabels:
      app: weatherforecast-api
  template:
    metadata:
      labels:
        app: weatherforecast-api
    spec:
      containers:
        - name: weatherforecast-api
          image: bogdanyarotsky/weatherforecast-api:latest
          ports:
            - containerPort: 80
