apiVersion: v1
kind: Service
metadata:
  name: weatherforecast-service
  namespace: app
spec:
  type: LoadBalancer # Creates a load balancer
  ports:
    - port: 80
  selector:
    app: weatherforecast-api
