name: Deploy to AKS

on:
  workflow_run:
    workflows: ["Docker Build and Push"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    needs: build-and-push # Ensure this runs after the Docker build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Kubernetes context
        uses: azure/setup-kubectl@v1

      - name: Deploy to AKS
        run: |
          kubectl apply -f ./WeatherForecastApi/deployment.yaml
          kubectl apply -f ./WeatherForecastApi/service.yaml
