name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - "WeatherForecastApi/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./WeatherForecastApi
          push: true
          tags: bogdanyarotsky/weatherforecast-api:latest
